syntax = "proto3";

option java_package = "com.brokenkernel.improvtools.datastore";
option java_multiple_files = true;


message UserSettings {
  // consider more detailed settings, enum for future proofing
  enum TimerHapticsMode {
    TIMER_HAPTICS_MODE_DEFAULT = 0;
    TIMER_HAPTICS_MODE_ALL = 1;
    TIMER_HAPTICS_MODE_NONE = 2;
  }

  // deprecated #1
  // https://analytics.google.com/analytics/web/#/a351396891p484696506/admin/consentmanagement
  bool allow_analytics_cookie_storage = 2;
  // deprecated #3

  TimerHapticsMode haptic_feedback_timer_mode = 4;
}
