[versions]
aboutLibraries = "12.0.0"
accompanistPermissions = "0.37.2"
activityCompose = "1.10.1"
agp = "8.9.1"
androidbrowserhelper = "2.6.0"
browser = "1.8.0"
dependencyAnalysis = "2.16.0"
annotation = "1.9.1"
composeBom = "2025.04.00"
coreKtx = "1.16.0"
androidXdatastore = "1.1.4"
espressoCore = "3.6.1"
espressoDevice = "1.0.1"
firebaseBom = "33.12.0"
firebaseCrashlyticsPlugin = "3.0.3"
firebasePerfPlugin = "1.4.2"
glanceAppwidget = "1.1.1"
googleGmsGoogleServices = "4.4.2"
guava = "33.4.8-android"
hilt = "2.56.2"
hiltNavigationCompose = "1.2.0"
inputMotionprediction = "1.0.0-beta05"
jacksonModuleKotlin = "2.18.3"
javaxInject = "1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.20"
kotlinxSerialization = "1.8.1"
ktlint = "12.2.0"
ksp = "2.1.20-2.0.0"
leakcanaryAndroid = "2.14"
lifecycleRuntimeKtx = "2.8.7"
lifecycleViewModelKtx = "2.8.7"
lintGradle = "1.0.0-alpha03"
loader = "1.1.0"
material3-adaptive-navigation-suite = "1.3.2"
materialIconsExtended = "1.7.8"
navigationCompose = "2.8.9"
navigationTesting = "2.8.9"
playServicesInstantapps = "18.1.0"
profileinstaller = "1.4.1"
protobuf = "0.9.5"
protobufJavalite = "4.30.2"
protoc = "4.30.2"
screengrab = "2.1.1"
startupRuntime = "1.2.0"
viewModelCompose = "2.8.7"
window = "1.3.0"
workRuntimeKtx = "2.10.0"
sortDependencies = "0.14"
zoomable = "2.6.0"
zoomableImageCoil3 = "0.15.1"



[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidbrowserhelper = { module = "com.google.androidbrowserhelper:androidbrowserhelper", version.ref = "androidbrowserhelper" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activityCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidXdatastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidXdatastore" }
androidx-datastore-datastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidXdatastore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-espresso-device = { module = "androidx.test.espresso:espresso-device", version.ref = "espressoDevice" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glanceAppwidget" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-input-motionprediction = { module = "androidx.input:input-motionprediction", version.ref = "inputMotionprediction" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModelKtx" }
androidx-lint-gradle = { module = "androidx.lint:lint-gradle", version.ref = "lintGradle" }
androidx-loader = { module = "androidx.loader:loader", version.ref = "loader" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-navigationTesting = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workRuntimeKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workRuntimeKtx" }
com-fasterxml-jackson-module-jacksonModuleKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
com-google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
com-google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
com-google-firebase-firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
com-google-firebase-firebasePerf = { module = "com.google.firebase:firebase-perf" }
com-google-protobuf-protobufJavalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobufJavalite" }
com-google-protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protoc" }
firebase-config = { module = "com.google.firebase:firebase-config" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinxSerialization" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
play-services-instantapps = { module = "com.google.android.gms:play-services-instantapps", version.ref = "playServicesInstantapps" }
tools-fastlane-screengrab = { group = "tools.fastlane", name = "screengrab", version.ref = "screengrab" }
net-engawapg-lib-zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
zoomable-image-coil3 = { module = "me.saket.telephoto:zoomable-image-coil3", version.ref = "zoomableImageCoil3" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }

[bundles]

# perf disabled because of
# issues with prod , "com-google-firebase-firebasePerf"
firebase = ["com-google-firebase-analytics", "com-google-firebase-crashlytics" ]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
aboutLibraries = { id="com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
firebaseCrashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebasePerfPlugin = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
dependencyAnalysis = { id ="com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortDependencies"}
#lint = { id = "com.android.lint" }
