# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Bump Version In Gradle File"
  lane :increment_gradle_version do
    increment_version_code(
          gradle_file_path: "app/build.gradle.kts",
    )
  end

  desc "Take Screenshots"
  lane :improv_tools_screenshots do
    capture_android_screenshots(
      clear_previous_screenshots: true,
      skip_open_summary: true,
      use_tests_in_packages: "com.brokenkernel.improvtools.deployment.screenshots",
      exit_on_test_failure: true,
    )
  end

  desc "Full Play Store Deployment"
  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

#     improv_tools_screenshots
#     increment_gradle_version
    current_build_number = android_get_version_code(
      gradle_file: "app/build.gradle.kts",
    )

    puts "Using build number: #{current_build_number}".yellow

    upload_to_play_store(
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      validate_only: true, ## TODO
      skip_upload_changelogs: false, ## TODO
      version_code: current_build_number
    )
  end
end
