# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Bump Version In Gradle File"
  lane :increment_gradle_version do
    ensure_git_branch(branch: 'master')
    increment_version_code(
          gradle_file_path: "app/build.gradle.kts",
    )
    current_build_number = android_get_version_code(
      gradle_file: "app/build.gradle.kts",
    )

    git_commit(
      path: "app/build.gradle.kts",
      message: "[fastlane] bump version code to " + current_build_number
    )
  end

  desc "Take Screenshots"
  lane :improv_tools_screenshots do
    build_for_screengrab
    capture_android_screenshots(
      clear_previous_screenshots: true,
      skip_open_summary: true,
      use_tests_in_packages: "com.brokenkernel.improvtools.deployment.screenshots",
      exit_on_test_failure: true,
      test_instrumentation_runner: "com.brokenkernel.improvtools.infrastructure.ImprovToolsTestRunner"
    )
  end

  desc "Full Play Store Deployment"
  lane :playstore do
    git_pull(
      only_tags: true,
      rebase: true,
    ) # only the tags, no commits
    ensure_git_status_clean
    increment_gradle_version
    current_build_number = android_get_version_code(
      gradle_file: "app/build.gradle.kts",
    )

    add_git_tag(
      grouping: "fastlane-builds",
      includes_lane: true,
      prefix: "v",
      build_number: current_build_number
    )


    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    # changelog_from_git_commits

    improv_tools_screenshots
    puts "Using build number: #{current_build_number}".yellow

    upload_to_play_store(
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
#       validate_only: true, ## TODO
      version_code: current_build_number
    )
  end
end
