baseURL = 'https://improvtools.brokenkernel.com/'
languageCode = 'en-us'

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]
[languages.en]
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.en.params]
title = 'Improv & Acting Tools'
description = "Improv & Acting Tools"

[params]
offlineSearch = true

[[cascade]]
type = "blog"
toc_root = true

  [cascade._target]
  path = "/news/**"

[[cascade]]
type = "docs"

  [cascade._target]
  path = "/**"

[[params.versions]]
  version = "master"

[module.hugoVersion]
extended = true
min = "0.146.4"
[[module.imports]]
path = "github.com/google/docsy"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
