name: run all android tests

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew test
