name: Dependency Submission

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'master' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v5

