name: 'Dependency Review'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
