name: "Validate Gradle Wrapper"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'master' ]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
